name: feature
description: Feature request
title: "[FR] <title>"
labels: [fr]
body:
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about your request.

  validations:
    required: false
